### PR TITLE
Make file cap/log persistance options public

### PR DESCRIPTION
**Pull request by joelekstrom**
Pardon my Swift-awkwardness - I just realized I forgot this when trying to integrate them into Buildasaur 😰 I suppose this requires another release...

### CODE REVIEW

**Comment by buildasaur** [comment]
## Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/07ec8c9e9cc1b2378c78ddb47b0f1d09/07ec8c9e9cc1b2378c78ddb47b0f2a74)

_Duration_: 1 hour, 24 seconds
_Result_: **0 error, failing state: internal-build-error**

**Comment by buildasaur** [comment]
## Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/honzadvysmbpr14.home/07ec8c9e9cc1b2378c78ddb47b0f1d09/07ec8c9e9cc1b2378c78ddb47b102af9)

_Duration_: 10 seconds
_Result_: **Perfect build!** All 14 tests passed. :+1:

**Comment by czechboy0** [comment]
No problem, making a release is just one fastlane command away :)

**Comment by czechboy0** [comment]
Done, here's the release: https://github.com/czechboy0/BuildaUtils/releases/tag/v0.2.6

**Comment by joelekstrom** [comment]
Thanks. :+1: I'll submit a patch for Buildasaur hopefully later today when I get home from work.

**Pull request merged**
